[package]
authors = ['Geoff Clements <ro2kz0@gmail.com>']
edition = '2018'
name = 'slimproto'
version = '0.1.0'

[dependencies]
bitflags = '1.2'
bytes = '1.0'
futures = "0.3"
mac_address = '1.1'
tokio = {version = '1.4', features = ['net', 'time']}
tokio-stream = "0.1"
tokio-util = {version = '0.6', features = ['codec']}

[dev-dependencies]
futures = "0.3"
tokio = {version = '1.4', features = ['macros', 'test-util']}
