[[example]]
name = 'discover'
path = 'discover.rs'

[[example]]
name = 'hello'
path = 'hello.rs'

[[example]]
name = 'boring'
path = 'boring.rs'

[[example]]
name = 'player'
path = 'player.rs'

[package]
edition = '2018'
name = 'examples'
publish = false
version = '0.0.0'

[dependencies]
futures = "0.3"
rodio = "0.13"
slimproto = {path = '../slimproto', version = '*'}
tokio = {version = '1.4', features = ['rt']}
