[[example]]
name = 'discover'
path = 'discover.rs'

# [[example]]
# name = 'monitor'
# path = 'monitor.rs'

[package]
edition = '2018'
name = 'examples'
publish = false
version = '0.0.0'

[dependencies]
slimproto = {path = '../slimproto', version = '*'}
tokio = {version = '1.4', features = ['full']}
